# Generated by Django 5.2 on 2025-04-13 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=20000)),
                ('timing', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.CharField(max_length=20)),
                ('room', models.CharField(max_length=20)),
            ],
        ),
    ]
