# Generated by Django 5.2 on 2025-04-13 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='chatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=20000)),
                ('timing', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.CharField(max_length=20)),
                ('room', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='chatroom',
            old_name='room',
            new_name='roomname',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='message',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='timing',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='user',
        ),
    ]
